### ISSUE TITLE
Issues when destroying multiple models from an ampersand-rest-collection

### ISSUE THREAD

**Issue by gpicazo** [AmpersandJS/ampersand-rest-collection#7]
I have an instance of a rest collection with multiple models. When I request to destroy models from said collection via model.destroy(...), the first delete works, but subsequent ones fail. Note that I am trying to avoid re-fetching the entire collection between deletes.

I've created a gist to outline what I am doing and the results that I am seeing:
https://gist.github.com/gpicazo/f94e61e3b085f9f5840b

In the comments, I've re-stated what the issue is and how I am currently working around it.

**Comment by HenrikJoreteg** [comment]
Given the age and lack of a clearly identifiable problem here i'm going to closes this.
